### PR TITLE
implement custom labels for targets

### PR DESCRIPTION
**Pull request by xykong**
# implement the ability to add custom label in config file.

In my case, this can be used in grafana dashboard filter.

## yaml config file example:

```
targets:
  - 8.8.8.8:
      category: dns
      alias: google-dns
  - 8.8.4.4:
      category: dns
      alias: google-dns
  - 2001:4860:4860::8888
  - 2001:4860:4860::8844
  - google.com:
      category: web

dns:
  refresh: 2m15s
  nameserver: 1.1.1.1

ping:
  interval: 2s
  timeout: 3s
  history-size: 42
  payload-size: 120

options:
  disableIPv6: false
```

## the metrics result:

```
# HELP ping_loss_ratio Packet loss from 0.0 to 1.0
# TYPE ping_loss_ratio gauge
ping_loss_ratio{alias="",category="",ip="2001:4860:4860::8844",ip_version="6",target="2001:4860:4860::8844"} 1
ping_loss_ratio{alias="",category="",ip="2001:4860:4860::8888",ip_version="6",target="2001:4860:4860::8888"} 1
ping_loss_ratio{alias="",category="web",ip="93.46.8.90",ip_version="4",target="google.com"} 1
ping_loss_ratio{alias="google-dns",category="dns",ip="8.8.4.4",ip_version="4",target="8.8.4.4"} 0
ping_loss_ratio{alias="google-dns",category="dns",ip="8.8.8.8",ip_version="4",target="8.8.8.8"} 0
# HELP ping_rtt_best_seconds Best round trip time in seconds
# TYPE ping_rtt_best_seconds gauge
ping_rtt_best_seconds{alias="google-dns",category="dns",ip="8.8.4.4",ip_version="4",target="8.8.4.4"} 0.06610533142089844
ping_rtt_best_seconds{alias="google-dns",category="dns",ip="8.8.8.8",ip_version="4",target="8.8.8.8"} 0.06759703826904297
# HELP ping_rtt_mean_seconds Mean round trip time in seconds
# TYPE ping_rtt_mean_seconds gauge
ping_rtt_mean_seconds{alias="google-dns",category="dns",ip="8.8.4.4",ip_version="4",target="8.8.4.4"} 0.06747858428955078
ping_rtt_mean_seconds{alias="google-dns",category="dns",ip="8.8.8.8",ip_version="4",target="8.8.8.8"} 0.06948183441162109
# HELP ping_rtt_std_deviation_seconds Standard deviation in seconds
# TYPE ping_rtt_std_deviation_seconds gauge
ping_rtt_std_deviation_seconds{alias="google-dns",category="dns",ip="8.8.4.4",ip_version="4",target="8.8.4.4"} 0.0013732500076293946
ping_rtt_std_deviation_seconds{alias="google-dns",category="dns",ip="8.8.8.8",ip_version="4",target="8.8.8.8"} 0.0018847919702529908
# HELP ping_rtt_worst_seconds Worst round trip time in seconds
# TYPE ping_rtt_worst_seconds gauge
ping_rtt_worst_seconds{alias="google-dns",category="dns",ip="8.8.4.4",ip_version="4",target="8.8.4.4"} 0.0688518295288086
ping_rtt_worst_seconds{alias="google-dns",category="dns",ip="8.8.8.8",ip_version="4",target="8.8.8.8"} 0.07136662292480468
# HELP ping_up ping_exporter version
# TYPE ping_up gauge
ping_up{version="1.0.0"} 1
```

### CODE REVIEW

**Comment by razem-io** [comment]
This would fix: 

* https://github.com/czerwonk/ping_exporter/issues/78
* https://github.com/czerwonk/ping_exporter/issues/33

**Comment by andreasmarkussen** [comment]
@czerwonk  - What is your perspective on this PR?

**Comment by LightningRhino** [comment]
Waiting for this feature, too. 😃

**Comment by Noodlesalat** [comment]
Wow, nice! Many thanks for taking the time @czerwonk! :)

**Comment by lZzozZl** [comment]
I think this is not working, i just try it out
Also is not given as an example in the main read.me

**Comment by aytugan** [comment]
@czerwonk thank you for adding labels to targets!
Could you please add to README example of tag? It is not clear how to use it.

**Comment by lZzozZl** [comment]
Thanx for updating. Still does not work for me.

**Comment by Noodlesalat** [comment]
A configuration example:
```
[...]
targets:
- dns.google:
    alias: Google DNS
[...]
```

corresponds to (truncated):
```
ping_rtt_best_seconds{alias="Google DNS",ip="8.8.8.8",ip_version="4",target="dns.google"} 0.000549456000328064
```

Hope this helps. Feel free to contact me with follow up questions. :)

**Comment by aytugan** [comment]
thank you @Noodlesalat !

**Pull request merged**
