### PR TITLE
Switch RTT metrics to use seconds instead of milliseconds

### PR DESCRIPTION
**Pull request by tdabasinskas**
As per [official Prometheus guidelines](https://prometheus.io/docs/practices/naming/#base-units), switching non-deprecated RTT metrics units from milliseconds to seconds and updating documentation accordingly.

Solves #16. As it's a breaking change, it should be released as part of a new major version.

### CODE REVIEW

**Comment by tdabasinskas** [comment]
Hi, @czerwonk,

Can you please look into this one?

**Comment by tdabasinskas** [comment]
@czerwonk ,

Maybe you had a chance to look into this?

**Comment by ijjjmsf** [comment]
@tdabasinskas why you want to change it?

**Comment by tdabasinskas** [comment]
Closing, as there were no comments for maintainers for 4 months.

**Pull request closed without merging**
